### ISSUE TITLE
incorrect type for `Request#is`

### ISSUE THREAD

**Issue by joprice** [glutinum-org/Glutinum#17]
The return type for the `is` method on `Request` is currently `string option`, which handles the presence of a body, but when the content-type header is missing, the return type will be a boolean: `If the request has no body, returns null. Returns false otherwise.`. So it seems the expected return type would be `U2<option<string>, bool>`.

 https://github.com/glutinum-org/Glutinum/blob/52b2f2487aa2195fb04751df72f607aa6980f4b7/glues/ExpressServeStaticCore/src/Glutinum.ExpressServeStaticCore.fs#L1435

**Comment by MangelMaxime** [comment]
@joprice Could you please send a PR?

The files in this repository have been crafted manually so we can make manual improvements.

**Comment by joprice** [comment]
Sounds good. I can put a pr up

**Comment by joprice** [comment]
This change was included in #18  https://github.com/glutinum-org/Glutinum/pull/18#issuecomment-2288333021
